# gateway_server/server_schemas.py
from pydantic import BaseModel, Field

class ClientRegistrationRequest(BaseModel):
    """
    Validates initial client identity claim before executing hybrid encapsulation pipelines.
    """
    client_id: str = Field(..., min_length=3, max_length=50, description="Unique identifier for the client endpoint (e.g., T490-Agent)")
    mldsa_public_key: str = Field(..., description="Hex-encoded ML-DSA-87 Public Verification Key for identity authentication")
    classical_public_key: str = Field(..., description="Hex-encoded Classical Public Key used in standard signature fallback checks")

class HybridHandshakePayload(BaseModel):
    """
    Strict payload verification for the post-quantum + classical hybrid key exchange.
    """
    client_id: str = Field(..., description="Unique client system identifier")
    mldem_ciphertext: str = Field(..., description="Hex-encoded ML-KEM-1024 Ciphertext generated by the client")
    ecdh_public_key: str = Field(..., description="Hex-encoded Classical Ephemeral X25519 Public Key from the client")
    client_signature: str = Field(..., description="NIST Digitally signed token hash verifying control plane integrity")
